---

- hosts: all
  become: true
  pre_tasks:

    - name: install Java
      tags: always,master
      package:
        name:
          - default-jre
        state: latest
        update_cache: yes
      changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: master
  become: true
  roles:
    - master
