- name: add ssh key for jenkins
  tags: always
  authorized_key:
    user: jenkins
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH32Upi/D/et7ZFQlsTGdimImijUawXO4QerH/Yt8PcP ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd